In [3]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/python/3.12.1/lib/python3.12/site-packages/numpy/__init__.py'>

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a=np.array([1,2,3,4,5,6])

In [8]:
a[2]=10

In [9]:
a

array([ 1,  2, 10,  4,  5,  6])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(4,12)

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Multi dimension array

In [13]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [17]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
n[0,1] = 20

In [19]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

To access row and row assignment

In [20]:
n[0]

array([ 1, 20,  3])

In [21]:
n[0]= [9,9,9]

In [22]:
n

array([[9, 9, 9],
       [4, 5, 6],
       [7, 8, 9]])

to fetch only column

In [23]:
n[:,1]

array([9, 5, 8])

Randomly generated arrays

In [26]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [27]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [28]:
np.random.seed(2)
100 * np.random.randn(5,2)

array([[ -41.67578474,   -5.62668272],
       [-213.61960957,  164.02708084],
       [-179.34355852,  -84.17473657],
       [  50.28814172, -124.52880866],
       [-105.79522189,  -90.90076149]])

In [29]:
np.random.seed(2)
np.random.randint(low=0,high=100,size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [30]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [31]:
a+1

array([1, 2, 3, 4, 5])

In [32]:
a*100

array([  0, 100, 200, 300, 400])

In [33]:
b = (10 + (a*2))**2/100

In [34]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [35]:
a+b

array([1.  , 2.44, 3.96, 5.56, 7.24])

Comparision operations

In [36]:
a

array([0, 1, 2, 3, 4])

In [38]:
a>=2

array([False, False,  True,  True,  True])

In [39]:
b<1

array([False, False, False, False, False])

In [40]:
b<4

array([ True,  True,  True,  True,  True])

In [41]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [42]:
a>b

array([False, False,  True,  True,  True])

In [43]:
a[a>b]

array([2, 3, 4])

In [44]:
a

array([0, 1, 2, 3, 4])

In [45]:
a

array([0, 1, 2, 3, 4])

In [49]:
a.min()



np.int64(0)

In [51]:
a.max()


np.int64(4)

In [52]:
a.std()

np.float64(1.4142135623730951)

In [4]:
u=np.array([2,4,5,6])
u

array([2, 4, 5, 6])

In [5]:
v=np.array([1,0,0,2])
v

array([1, 0, 0, 2])

In [14]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]

    n=u.shape[0]

    result = 0.0
    for i in range(n):
        result=result+u[i]*v[i]

    return result

In [15]:
vector_vector_multiplication(u,v)

np.float64(14.0)

identity matrix

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])